[package]
name = "binscope"
version = "0.0.1"
authors = ["Andrew Dunham <andrew@du.nham.ca>"]

[dependencies]
ansi_term = "*"
byteorder = "*"
clap = "*"
fern = "0.3"
libc = "*"
log = "0.3"
mmap = "*"
nom = "~1.0.0"
time = "0.2"
